### PR TITLE
Remove isMounted()

### PR DESCRIPTION
**Pull request by STRML**
Deprecated in 0.13 and removed in 0.14.

### CODE REVIEW

**Comment by manuelmazzuola** [comment]
Please merge :+1:

**Comment by BinaryMuse** [comment]
Beautiful, thanks

**Comment by STRML** [comment]
<3

**Comment by BinaryMuse** [comment]
Am I crazy or did this PR originally have a ton more stuff in it?

Published as 1.7.2 :) Thanks again.

**Comment by STRML** [comment]
I don't think so. Maybe GitHub diffing strangely? Or you haven't had enough caffeine

**Pull request merged**
