### PR TITLE
#105 store refer to it's own state

### PR DESCRIPTION
**Pull request by andy-williams**
Changed payload to pass the index instead of todo object.

### CODE REVIEW

**Comment by BinaryMuse** [comment]
Thanks, @andy-williams, this is a great improvement. What do you think about using an incrementing ID (similar to the [recipe example](https://github.com/BinaryMuse/fluxxor/blob/master/examples/react-router/app/stores/recipe_store.jsx#L9)) so we don't have to rely on the index of the item in the store's internal array? The index works but is probably not really a great practice in most cases, and this might be a good time to address it.

**Comment by andy-williams** [comment]
@BinaryMuse Awesome. I've done that change now. Please review.

**Comment by BinaryMuse** [comment]
Thanks much; sorry it took so long to get this merged.

**Comment by andy-williams** [comment]
No problem :)

**Pull request merged**
