### PR TITLE
Move to lodash v 3.0.1

### PR DESCRIPTION
**Pull request by marcus**
Update to lodash 3.0.1 as discussed here https://github.com/BinaryMuse/fluxxor/issues/98

### CODE REVIEW

**Comment by BinaryMuse** [comment]
Thanks for the PR, @marcus! Would you mind amending the commit to not include the files from `build/`? I'll generate those with a versioned build.

Otherwise this looks great, thanks again!

**Comment by marcus** [comment]
Should be good to go!

**Comment by BinaryMuse** [comment]
Thanks!

**Comment by jdalton** [comment]
Since you're using the modern build you can just use `lodash` now. For example `require('lodash/lang/clone')` also aliases are supported now so you can reference `require('lodash/collection/each')` too.

**Pull request merged**
